version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/chat.cursor.style
    overwrite: true

file_exists_behavior: OVERWRITE

permissions:
  - object: /var/www/chat.cursor.style
    owner: ubuntu
    group: ubuntu
    mode: 755
    type:
      - directory
  - object: /var/www/chat.cursor.style
    owner: ubuntu
    group: ubuntu
    mode: 644
    type:
      - file

hooks:
  AfterInstall:
    - location: scripts/after-install.sh
      timeout: 600
      runas: root